"""create_domain_models_v0_2

Revision ID: 657650f1297c
Revises: 
Create Date: 2026-06-29 14:14:51.624542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657650f1297c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity'], unique=False)
    op.create_index('ix_audit_logs_entity_entity_id', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_table('telegram_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('has_photo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', name='uq_telegram_users_telegram_id')
    )
    op.create_index('ix_telegram_users_telegram_id', 'telegram_users', ['telegram_id'], unique=False)
    op.create_index('ix_telegram_users_username', 'telegram_users', ['username'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('telegram_id', name='uq_users_telegram_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('blacklists',
    sa.Column('telegram_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blacklists_created_at', 'blacklists', ['created_at'], unique=False)
    op.create_index('ix_blacklists_source', 'blacklists', ['source'], unique=False)
    op.create_index('ix_blacklists_telegram_user_id', 'blacklists', ['telegram_user_id'], unique=False)
    op.create_table('reputations',
    sa.Column('telegram_user_id', sa.UUID(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('bot_votes', sa.Integer(), nullable=False),
    sa.Column('human_votes', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id', name='uq_reputations_telegram_user_id')
    )
    op.create_index('ix_reputations_reputation_score', 'reputations', ['reputation_score'], unique=False)
    op.create_index('ix_reputations_telegram_user_id', 'reputations', ['telegram_user_id'], unique=False)
    op.create_table('telegram_bots',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=False),
    sa.Column('bot_username', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_username', name='uq_telegram_bots_bot_username')
    )
    op.create_index('ix_telegram_bots_bot_username', 'telegram_bots', ['bot_username'], unique=False)
    op.create_index('ix_telegram_bots_owner_id', 'telegram_bots', ['owner_id'], unique=False)
    op.create_table('whitelists',
    sa.Column('telegram_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whitelists_approved_by', 'whitelists', ['approved_by'], unique=False)
    op.create_index('ix_whitelists_created_at', 'whitelists', ['created_at'], unique=False)
    op.create_index('ix_whitelists_telegram_user_id', 'whitelists', ['telegram_user_id'], unique=False)
    op.create_table('telegram_channels',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('invite_link', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['telegram_bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id', name='uq_telegram_channels_telegram_chat_id')
    )
    op.create_index('ix_telegram_channels_bot_id', 'telegram_channels', ['bot_id'], unique=False)
    op.create_index('ix_telegram_channels_is_active', 'telegram_channels', ['is_active'], unique=False)
    op.create_index('ix_telegram_channels_owner_id', 'telegram_channels', ['owner_id'], unique=False)
    op.create_index('ix_telegram_channels_telegram_chat_id', 'telegram_channels', ['telegram_chat_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MANUAL_REVIEW', name='join_request_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_join_requests_channel_id', 'join_requests', ['channel_id'], unique=False)
    op.create_index('ix_join_requests_channel_user_created', 'join_requests', ['channel_id', 'telegram_user_id', 'created_at'], unique=False)
    op.create_index('ix_join_requests_status', 'join_requests', ['status'], unique=False)
    op.create_index('ix_join_requests_telegram_user_id', 'join_requests', ['telegram_user_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('join_request_id', sa.UUID(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'MANUAL_REVIEW', name='analysis_decision'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['join_request_id'], ['join_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analyses_created_at', 'ai_analyses', ['created_at'], unique=False)
    op.create_index('ix_ai_analyses_decision', 'ai_analyses', ['decision'], unique=False)
    op.create_index('ix_ai_analyses_join_request_id', 'ai_analyses', ['join_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_analyses_join_request_id', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_decision', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_created_at', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_join_requests_telegram_user_id', table_name='join_requests')
    op.drop_index('ix_join_requests_status', table_name='join_requests')
    op.drop_index('ix_join_requests_channel_user_created', table_name='join_requests')
    op.drop_index('ix_join_requests_channel_id', table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index('ix_telegram_channels_telegram_chat_id', table_name='telegram_channels')
    op.drop_index('ix_telegram_channels_owner_id', table_name='telegram_channels')
    op.drop_index('ix_telegram_channels_is_active', table_name='telegram_channels')
    op.drop_index('ix_telegram_channels_bot_id', table_name='telegram_channels')
    op.drop_table('telegram_channels')
    op.drop_index('ix_whitelists_telegram_user_id', table_name='whitelists')
    op.drop_index('ix_whitelists_created_at', table_name='whitelists')
    op.drop_index('ix_whitelists_approved_by', table_name='whitelists')
    op.drop_table('whitelists')
    op.drop_index('ix_telegram_bots_owner_id', table_name='telegram_bots')
    op.drop_index('ix_telegram_bots_bot_username', table_name='telegram_bots')
    op.drop_table('telegram_bots')
    op.drop_index('ix_reputations_telegram_user_id', table_name='reputations')
    op.drop_index('ix_reputations_reputation_score', table_name='reputations')
    op.drop_table('reputations')
    op.drop_index('ix_blacklists_telegram_user_id', table_name='blacklists')
    op.drop_index('ix_blacklists_source', table_name='blacklists')
    op.drop_index('ix_blacklists_created_at', table_name='blacklists')
    op.drop_table('blacklists')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_telegram_users_username', table_name='telegram_users')
    op.drop_index('ix_telegram_users_telegram_id', table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
